apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.clientPort | default 2379 }}
      targetPort: client
      protocol: TCP
      name: client
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.service.metricsPort | default 2381 }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "etcd.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.service.clientPort | default 2379 }}
      targetPort: client
      protocol: TCP
      name: client
    - port: {{ .Values.service.peerPort | default 2380 }}
      targetPort: peer
      protocol: TCP
      name: peer
  selector:
    {{- include "etcd.selectorLabels" . | nindent 4 }}
