{{- if and .Values.config.content (not .Values.config.existingConfigmap)}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}-config
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
data:
  redis.conf: |
    {{- .Values.config.content | nindent 4 }}
{{- end }}