{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "clickhouse.annotations" . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (include "clickhouse.fullname" .)) }}
  {{- $existingPassword := "" }}
  {{- if and $existingSecret $existingSecret.data }}
    {{- $existingPassword = index $existingSecret.data "clickhouse-password" }}
  {{- end }}
  {{- $password := $existingPassword | default (.Values.auth.password | default (randAlphaNum 32) | b64enc) }}
  {{- $host := printf "%s.%s.svc" (include "clickhouse.fullname" .) .Release.Namespace }}
  {{- $tcpPort := .Values.service.tcpPort | toString }}
  {{- $httpPort := .Values.service.httpPort | toString }}
  {{- $username := .Values.auth.username }}
  {{- $database := .Values.auth.database }}
  clickhouse-password: {{ $password | quote }}
  host: {{ $host | b64enc | quote }}
  tcp-port: {{ $tcpPort | b64enc | quote }}
  http-port: {{ $httpPort | b64enc | quote }}
  username: {{ $username | b64enc | quote }}
  database: {{ $database | b64enc | quote }}
  uri: {{ printf "clickhouse://%s:%s@%s:%s/%s" $username ($password | b64dec) $host $tcpPort $database | b64enc | quote }}
{{- end }}
