{{- $hasInitScripts := or .Values.initdb.scripts .Values.initdb.scriptsConfigMap -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "clickhouse.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "clickhouse.annotations" . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "clickhouse.fullname" . }}-headless
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "clickhouse.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- $annotations := merge .Values.podAnnotations .Values.commonAnnotations }}
      {{- with $annotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "clickhouse.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "clickhouse.serviceAccountName" . }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- with (include "clickhouse.imagePullSecrets" .) }}
{{- . | nindent 6 }}
{{- end }}
      securityContext: {{ include "cloudpirates.renderPodSecurityContext" . | nindent 8 }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      enableServiceLinks: {{ .Values.global.enableServiceLinks }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext: {{ include "cloudpirates.renderContainerSecurityContext" . | nindent 12 }}
          image: {{ include "clickhouse.image" . }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          {{- if .Values.command }}
          command: {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args: {{- toYaml .Values.args | nindent 12 }}
          {{- end }}
          env:
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "clickhouse.secretName" . }}
                  key: {{ include "clickhouse.passwordKey" . }}
            - name: CLICKHOUSE_DB
              value: {{ .Values.auth.database | quote }}
            - name: CLICKHOUSE_USER
              value: {{ .Values.auth.username | quote }}
            - name: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
              value: "1"
            {{- with .Values.extraEnvVars }}
{{ toYaml . | indent 12 }}
            {{- end }}
          {{- if .Values.extraEnvVarsSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.extraEnvVarsSecret }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
              protocol: TCP
            - name: tcp
              containerPort: {{ .Values.service.tcpPort }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Values.persistence.volumeName }}
              mountPath: /var/lib/clickhouse
              {{- if .Values.persistence.subPath }}
              subPath: {{ .Values.persistence.subPath }}
              {{- end }}
            - name: config
              mountPath: /etc/clickhouse-server/config.d/kubernetes.xml
              subPath: kubernetes.xml
            - name: users-config
              mountPath: /etc/clickhouse-server/users.d/kubernetes.xml
              subPath: kubernetes.xml
            - name: tmp
              mountPath: /tmp
            {{- if $hasInitScripts }}
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
        {{- if .Values.metrics.enabled }}
        - name: metrics
          image: "{{ .Values.metrics.image.registry }}/{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}"
          imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
          env:
            - name: CLICKHOUSE_USER
              value: {{ .Values.auth.username | quote }}
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "clickhouse.secretName" . }}
                  key: {{ include "clickhouse.passwordKey" . }}
            - name: CLICKHOUSE_URL
              value: "http://localhost:{{ .Values.service.httpPort }}/"
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.service.port }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /metrics
              port: metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
          {{- with .Values.metrics.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
      volumes:
        {{- if not .Values.persistence.enabled }}
        - name: {{ .Values.persistence.volumeName }}
          emptyDir: {}
        {{- end }}
        {{- if .Values.persistence.existingClaim }}
        - name: {{ .Values.persistence.volumeName }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        {{- end }}
        - name: config
          configMap:
            name: {{ include "clickhouse.configmapName" . }}
        - name: users-config
          configMap:
            name: {{ include "clickhouse.usersConfigmapName" . }}
        - name: tmp
          emptyDir: {}
        {{- if $hasInitScripts }}
        - name: init-scripts
          configMap:
            name: {{ include "clickhouse.initdb.scriptsCM" . }}
            defaultMode: 0755
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  {{- if .Values.persistentVolumeClaimRetentionPolicy.enabled }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: {{ .Values.persistentVolumeClaimRetentionPolicy.whenDeleted }}
    whenScaled: {{ .Values.persistentVolumeClaimRetentionPolicy.whenScaled }}
  {{- end }}
  {{- if not .Values.persistence.existingClaim }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.persistence.volumeName }}
      {{- with $labels := merge (include "clickhouse.selectorLabels" . | fromYaml) .Values.persistence.labels .Values.podLabels }}
      labels:
        {{- toYaml $labels | nindent 8 }}
      {{- end }}
      {{- with .Values.persistence.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      accessModes:
        {{- range .Values.persistence.accessModes }}
        - {{ . | quote }}
        {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
      {{- if .Values.persistence.storageClass }}
      {{- if (eq "-" .Values.persistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: {{ .Values.persistence.storageClass | quote }}
      {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
