{{- if .Values.config.extraEnvVars }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "minio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "minio.annotations" . | nindent 4 }}
  {{- end }}
data:
  {{- range .Values.config.extraEnvVars }}
  {{- if and .name .value }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}
  {{- end }}
{{- end }}